openapi: 3.1.0

info:
  title: nemmy API
  description: |
    nemmyで利用するAPIの仕様書です。<br />
    http://localhost:8080/apiは仮のURLです。
  version: 1.0.0

servers:
  - url: http://localhost:8080/api

paths:
  /users/{userName}/subjects:
    get:
      summary: ユーザーに紐づく教材の一覧を取得
      operationId: listUserSubjects
      tags:
        - subjects
      parameters:
        - name: userName
          in: path
          required: true
          description: ユーザーネーム
          schema:
            type: string
      responses:
        "200":
          description: ユーザーに紐づく教材の一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Subject"
    post:
      summary: ユーザーに紐づく教材を作成
      operationId: createUserSubject
      tags:
        - subjects
      parameters:
        - name: userName
          in: path
          required: true
          description: ユーザーネーム
          schema:
            type: string
      requestBody:
        description: ユーザーに紐づく教材の情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                name:
                  type: string
                description:
                  type: string
              required:
                - userName
                - name
      responses:
        "201":
          description: ユーザーに紐づく教材の作成
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subject"
  /users/{userName}/subjects/{subjectId}:
    get:
      summary: ユーザーに紐づく教材の詳細を取得
      operationId: getUserSubject
      tags:
        - subjects
      parameters:
        - name: userName
          in: path
          required: true
          description: ユーザーネーム
          schema:
            type: string
        - name: subjectId
          in: path
          required: true
          description: 教材のID
          schema:
            type: string
      responses:
        "200":
          description: ユーザーに紐づく教材の詳細
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subject"
    put:
      summary: ユーザーに紐づく教材の詳細を更新
      operationId: updateUserSubject
      tags:
        - subjects
      parameters:
        - name: userName
          in: path
          required: true
          description: ユーザーネーム
          schema:
            type: string
        - name: subjectId
          in: path
          required: true
          description: 教材のID
          schema:
            type: string
      requestBody:
        description: ユーザーに紐づく教材の情報
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Subject"
      responses:
        "200":
          description: ユーザーに紐づく教材の更新
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subject"
    delete:
      summary: ユーザーに紐づく教材を削除
      operationId: deleteUserSubject
      tags:
        - subjects
      parameters:
        - name: userName
          in: path
          required: true
          description: ユーザーネーム
          schema:
            type: string
        - name: subjectId
          in: path
          required: true
          description: 教材のID
          schema:
            type: string
      responses:
        "204":
          description: ユーザーに紐づく教材の削除

components:
  schemas:
    Subject:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        userName:
          type: string
        name:
          type: string
        description:
          type: string
