openapi: 3.0.0
info:
  title: nemmy API
  description: |
    nemmyで利用するAPIの仕様書です。<br />
    http://localhost:8080/apiは仮のURLです。
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /users/{userId}/subjects:
    get:
      summary: ユーザーに紐づく教材の一覧を取得
      operationId: listUserSubjects
      tags:
        - users
        - subjects
      parameters:
        - name: userId
          in: path
          required: true
          description: ユーザーのID
          schema:
            type: string
      responses:
        "200":
          description: ユーザーに紐づく教材の一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Subject"
components:
  schemas:
    Subject:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
