post-merge:
  parallel: true
  commands:
    frontend-dependencies-update:
      root: "frontend/"
      run: pnpm install --frozen-lockfile
    swagger-dependencies-update:
      root: "swagger/"
      run: pnpm install --frozen-lockfile
