name: CI backend

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    working-directory: backend

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: backend

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./backend/go.mod"
          cache-dependency-path: "./backend/go.sum"

      - name: Get dependencies
        run: go mod download

      - name: Format Go code
        run: go fmt ./...

      - name: Build
        run: go build -v ./...
